### ISSUE TITLE
Uncaught ReferenceError: g is not defined

### ISSUE THREAD

**Issue by threebodymath** [svnpenn/bm#14]
Tried this link: https://www.youtube.com/watch?v=kPcDfLrzx3Y, which was mentioned in issue #10 and saw the message in the title.

**Comment by svnpenn** [comment]
@threebodymath I can repro this, will try to check it when I get home

**Comment by svnpenn** [comment]
I have a fix for this, will try to commit today

**Comment by svnpenn** [comment]
I have discovered a method that does not require XMLHttpRequest to decode signatures. This should significantly reduce the complexity of the code. I will try to commit today

**Comment by svnpenn** [comment]
I have discovered a method that does not require XMLHttpRequest to decode
signatures. This should significantly reduce the complexity of the code.
Example:

~~~
ya = yt.player.Application.create('player-api', ytplayer.config).getVideoData();
JSON.stringify(ya.b.b["133"].C.b, 0, 2);
"{
  "o": "https://r3---sn-q4f7sn7r.googlevideo.com/videoplayback?sver=3&keepalive=yes&dur=420.833&lmt=1423895085713162&source=youtube&ms=au&id=o-AMlVeu--sVOZqEsiPunIEUNbAllSoBQhIrX_ZCcn3Ght&ei=ofmUV-3BDsmprQaXmLeYDQ&mv=m&gcr=us&mn=sn-q4f7sn7r&mm=31&key=yt6&ip=2602%3A306%3A36d6%3A1d60%3Aa532%3Ae638%3Aaada%3Ab38&pl=52&initcwndbps=587500&nh=IgpwcjAyLmRmdzA2KgkxMjcuMC4wLjE&expire=1469402625&ipbits=0&mt=1469380474&requiressl=yes&clen=2873155&mime=video%2Fmp4&upn=Bu71E_sB--M&itag=133&gir=yes&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9416891%2C9422596%2C9428398%2C9430794%2C9431012%2C9433096%2C9433380%2C9433946%2C9435384%2C9435526%2C9435666%2C9435876%2C9437066%2C9437368%2C9437552%2C9437654%2C9437742%2C9438140%2C9438518%2C9438663%2C9438784%2C9439585%2C9439652%2C9440376%2C9440880%2C9442030%2C9442424&cpn=o-BY5YY__ra3Vnqn",
  "C": "",
  "A": "",
  "B": "",
  "b": {
    "alr": "yes",
    "keepalive": "yes",
    "ratebypass": "yes",
    "mime": "video%2Fmp4",
    "signature": "CAD580350B5BB57C5795237D68BF44A9A96D220F.4E78F64427905EE974E706F882C37B09E5C62C31",
    "c": "WEB",
    "cver": "1.20160721"
  },
  "g": ""
}"
~~~

This object includes the URL with encoded signature removed, as well as the
decoded signature.

**Comment by svnpenn** [comment]
https://github.com/YePpHa/YouTubeCenter/issues/1083

**Comment by Yonezpt** [comment]
Got here because of the reference in the specific thread and thought I would give you some suggestions.

Don't build static pointers based on dynamic pointers. The YouTube scripts are always minified and they often change, on average every 2 days a new player script is pushed. This means that those pointers you are using will eventually change every 2 days, at worst.

By dynamic pointers I mean each one of these letters "b.b[value].C.b"

Instead use more stable pointers, like patterns and/or global structures.

I discussed here (https://github.com/YePpHa/YouTubeCenter/issues/2098#issuecomment-157497362) where the algorithm decoder was located on the player script received on that day, and its structure. With that information you can use regex to pull the most updated algorithm decoder directly from the YouTube player script. It is commonly made up of 2 parts, the main function which receives the signature, sends for decoding and returns it (function named `$q`, at that time) and the secondary object which holds the methods of signature transformation used by the main function (object named `ar`, at that time)

You will still have to fetch the player js file to read the algorithm, but at least you will no longer have your script outdated every 2 days or so. If you have some sort of storing data in your program you can store the algorithm pattern for a certain player js file to avoid fetching the same one if you have already decoded in the past.

**Comment by svnpenn** [comment]
@Yonezpt downloading the JS file is the exact problem my method above solves, I am surely not going to go back to it.

It is certainly easily to `.map` or `.filter` a JS object than it is to download, eval and parse a Same-origin violating JS file. Good day sir.

**Comment by svnpenn** [comment]
@Yonezpt downloading the JS file is the exact problem my method above solves, I am surely not going to go back to it.

It is certainly easier to `.map` or `.filter` a JS object than it is to download, eval and parse a Same-origin violating JS file. My comment above is merely a proof of concept, preceeding my commit. Good day sir.

**Comment by svnpenn** [comment]
Here is where I am at so far:

~~~js
// create player
jul = yt.player.Application.create('player-api', ytplayer.config).getVideoData();

// turn object into string, avoiding cyclic object values
kil = [];
lim = JSON.stringify(jul, function(mik, nov) {
  if (nov != null && typeof nov == 'object') {
    if (kil.indexOf(nov) != -1) return;
    kil.push(nov);
  }
  return nov;
});

// filter out URLs with signature, they are duplicates
osc = lim.match(/https:[^"]+videoplayback[^"]+/g)
  .filter(pap => pap.indexOf('signature') == -1);
// more duplicate filtering
que = osc.filter((item, pos) => osc.indexOf(item) == pos);
~~~

**que** is an array of direct video links. I still need to parse the signatures,
but that shouldn’t be too hard.

**Comment by svnpenn** [comment]
This code returns an array of direct URLs, with the encoded signature removed,
and decoded signature added:

~~~js
seen = [];
function replacer(key, val) {
  if (val != null && typeof val == 'object') {
    if (seen.indexOf(val) != -1) return;
    seen.push(val);
  }
  return val;
}

function uniq(item, pos, self) {
  return self.indexOf(item) == pos;
}

// create player
wh = yt.player.Application.create('player-api', ytplayer.config).getVideoData();
// turn object into string, avoiding cyclic object values
xr = JSON.stringify(wh, replacer);
// get unique URLs
ya = xr.match(/https:[^"]+videoplayback[^"]+/g).filter(str => str.length < 1000).filter(uniq);
// get unique signatures
zu = xr.match(/[0123456789ABCDEF.]+(?=")/g).filter(str => str.length > 20).filter(uniq);
// combine
ya.map((item, pos) => item + '&signature=' + zu[pos]);
~~~

**Comment by svnpenn** [comment]
This code returns an array of direct URLs, with the encoded signature removed,
and decoded signature added:

~~~js
seen = [];
function replacer(key, val) {
  if (val != null && typeof val == 'object') {
    if (seen.indexOf(val) != -1) return;
    seen.push(val);
  }
  return val;
}

function uniq(item, pos, self) {
  return self.indexOf(item) == pos;
}

// create player
wh = yt.player.Application.create('player-api', ytplayer.config).getVideoData();
// turn object into string, avoiding cyclic object values
xr = JSON.stringify(wh, replacer);
// get unique URLs
ya = xr.match(/https:[^"]+videoplayback[^"]+/g)
  .filter(str => str.length < 1000).filter(uniq);
// get unique signatures
zu = xr.match(/[0123456789ABCDEF.]+(?=")/g)
  .filter(str => str.length > 20).filter(uniq);
// combine
ya.map((item, pos) => item + '&signature=' + zu[pos]);
~~~

I have a working private copy of the bookmarklet with these changes. I need to
do a little more testing; will try to commit soon.

**Comment by svnpenn** [comment]
@threebodymath I pushed a commit with a fix
